<?php
/**
 * FluentBooking - Appointment Scheduling & Booking Solution — WP Abilities API adapter
 * Generated by wp-ability-scanner on 2026-03-19
 * Drop into wp-content/mu-plugins/ — zero changes to FluentBooking - Appointment Scheduling & Booking Solution required.
 * @license GPL-2.0-or-later
 */
defined( 'ABSPATH' ) || exit;

// Categories use wp_abilities_api_categories_init hook
add_action( 'wp_abilities_api_categories_init', function(): void {
    wp_register_ability_category( 'fluent-booking', [
        'label'       => __( 'FluentBooking - Appointment Scheduling & Booking Solution', 'fluent-booking' ),
        'description' => __( 'AI abilities for FluentBooking - Appointment Scheduling & Booking Solution.', 'fluent-booking' ),
    ] );
} );

// Abilities use wp_abilities_api_init hook
add_action( 'wp_abilities_api_init', function(): void {

    wp_register_ability( 'fluent-booking/get-type', [
        'label'               => __( 'Get Type', 'fluent-booking' ),
        'description'         => __( 'Get type via FluentBookingCustomGroupSelect::get_type().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: FluentBookingCustomGroupSelect::get_type()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-name', [
        'label'               => __( 'Get Name', 'fluent-booking' ),
        'description'         => __( 'Get name via FcalBookings::get_name().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: FcalBookings::get_name()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-title', [
        'label'               => __( 'Get Title', 'fluent-booking' ),
        'description'         => __( 'Get title via FcalBookings::get_title().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: FcalBookings::get_title()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-icon', [
        'label'               => __( 'Get Icon', 'fluent-booking' ),
        'description'         => __( 'Get icon via FcalBookings::get_icon().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: FcalBookings::get_icon()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-categories', [
        'label'               => __( 'Get Categories', 'fluent-booking' ),
        'description'         => __( 'Get categories via FcalBookings::get_categories().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: FcalBookings::get_categories()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-keywords', [
        'label'               => __( 'Get Keywords', 'fluent-booking' ),
        'description'         => __( 'Get keywords via FcalBookings::get_keywords().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: FcalBookings::get_keywords()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-name-2', [
        'label'               => __( 'Get Name', 'fluent-booking' ),
        'description'         => __( 'Get name via FcalCalendar::get_name().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: FcalCalendar::get_name()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-title-2', [
        'label'               => __( 'Get Title', 'fluent-booking' ),
        'description'         => __( 'Get title via FcalCalendar::get_title().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: FcalCalendar::get_title()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-icon-2', [
        'label'               => __( 'Get Icon', 'fluent-booking' ),
        'description'         => __( 'Get icon via FcalCalendar::get_icon().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: FcalCalendar::get_icon()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-categories-2', [
        'label'               => __( 'Get Categories', 'fluent-booking' ),
        'description'         => __( 'Get categories via FcalCalendar::get_categories().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: FcalCalendar::get_categories()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-keywords-2', [
        'label'               => __( 'Get Keywords', 'fluent-booking' ),
        'description'         => __( 'Get keywords via FcalCalendar::get_keywords().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: FcalCalendar::get_keywords()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-name-3', [
        'label'               => __( 'Get Name', 'fluent-booking' ),
        'description'         => __( 'Get name via FcalCalendarEvent::get_name().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: FcalCalendarEvent::get_name()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-title-3', [
        'label'               => __( 'Get Title', 'fluent-booking' ),
        'description'         => __( 'Get title via FcalCalendarEvent::get_title().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: FcalCalendarEvent::get_title()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-icon-3', [
        'label'               => __( 'Get Icon', 'fluent-booking' ),
        'description'         => __( 'Get icon via FcalCalendarEvent::get_icon().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: FcalCalendarEvent::get_icon()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-categories-3', [
        'label'               => __( 'Get Categories', 'fluent-booking' ),
        'description'         => __( 'Get categories via FcalCalendarEvent::get_categories().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: FcalCalendarEvent::get_categories()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-keywords-3', [
        'label'               => __( 'Get Keywords', 'fluent-booking' ),
        'description'         => __( 'Get keywords via FcalCalendarEvent::get_keywords().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: FcalCalendarEvent::get_keywords()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-id', [
        'label'               => __( 'Get Id', 'fluent-booking' ),
        'description'         => __( 'Get id via ActionScheduler_ActionClaim::get_id().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_ActionClaim::get_id()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-actions', [
        'label'               => __( 'Get Actions', 'fluent-booking' ),
        'description'         => __( 'Get actions via ActionScheduler_ActionClaim::get_actions().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_ActionClaim::get_actions()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-stored-action', [
        'label'               => __( 'Get Stored Action', 'fluent-booking' ),
        'description'         => __( 'Get stored action via ActionScheduler_ActionFactory::get_stored_action().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_ActionFactory::get_stored_action()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-date', [
        'label'               => __( 'Get Date', 'fluent-booking' ),
        'description'         => __( 'Get date via ActionScheduler_LogEntry::get_date().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_LogEntry::get_date()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-action-id', [
        'label'               => __( 'Get Action Id', 'fluent-booking' ),
        'description'         => __( 'Get action id via ActionScheduler_LogEntry::get_action_id().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_LogEntry::get_action_id()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-message', [
        'label'               => __( 'Get Message', 'fluent-booking' ),
        'description'         => __( 'Get message via ActionScheduler_LogEntry::get_message().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_LogEntry::get_message()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-expiration', [
        'label'               => __( 'Get Expiration', 'fluent-booking' ),
        'description'         => __( 'Get expiration via ActionScheduler_OptionLock::get_expiration().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_OptionLock::get_expiration()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/delete-old-actions', [
        'label'               => __( 'Delete Old Actions', 'fluent-booking' ),
        'description'         => __( 'Delete old actions via ActionScheduler_QueueCleaner::delete_old_actions().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id'    => [ 'type' => 'integer', 'description' => 'Item ID'               ],
                    'force' => [ 'type' => 'boolean', 'description' => 'Bypass trash', 'default' => false ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_QueueCleaner::delete_old_actions()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-versions', [
        'label'               => __( 'Get Versions', 'fluent-booking' ),
        'description'         => __( 'Get versions via ActionScheduler_Versions::get_versions().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_Versions::get_versions()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/delete-all-action-comments', [
        'label'               => __( 'Delete All Action Comments', 'fluent-booking' ),
        'description'         => __( 'Delete all action comments via ActionScheduler_WPCommentCleaner::delete_all_action_comments().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id'    => [ 'type' => 'integer', 'description' => 'Item ID'               ],
                    'force' => [ 'type' => 'boolean', 'description' => 'Bypass trash', 'default' => false ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_WPCommentCleaner::delete_all_action_comments()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-datetime-object', [
        'label'               => __( 'Get Datetime Object', 'fluent-booking' ),
        'description'         => __( 'Get datetime object via ActionScheduler::get_datetime_object().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler::get_datetime_object()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-sortable-columns', [
        'label'               => __( 'Get Sortable Columns', 'fluent-booking' ),
        'description'         => __( 'Get sortable columns via ActionScheduler_Abstract_ListTable::get_sortable_columns().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_Abstract_ListTable::get_sortable_columns()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-columns', [
        'label'               => __( 'Get Columns', 'fluent-booking' ),
        'description'         => __( 'Get columns via ActionScheduler_Abstract_ListTable::get_columns().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_Abstract_ListTable::get_columns()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-allowed-concurrent-batches', [
        'label'               => __( 'Get Allowed Concurrent Batches', 'fluent-booking' ),
        'description'         => __( 'Get allowed concurrent batches via ActionScheduler_Abstract_QueueRunner::get_allowed_concurrent_batches().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_Abstract_QueueRunner::get_allowed_concurrent_batches()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-first-date', [
        'label'               => __( 'Get First Date', 'fluent-booking' ),
        'description'         => __( 'Get first date via ActionScheduler_Abstract_RecurringSchedule::get_first_date().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_Abstract_RecurringSchedule::get_first_date()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-recurrence', [
        'label'               => __( 'Get Recurrence', 'fluent-booking' ),
        'description'         => __( 'Get recurrence via ActionScheduler_Abstract_RecurringSchedule::get_recurrence().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_Abstract_RecurringSchedule::get_recurrence()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-next', [
        'label'               => __( 'Get Next', 'fluent-booking' ),
        'description'         => __( 'Get next via ActionScheduler_Abstract_Schedule::get_next().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_Abstract_Schedule::get_next()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-date-2', [
        'label'               => __( 'Get Date', 'fluent-booking' ),
        'description'         => __( 'Get date via ActionScheduler_Abstract_Schedule::get_date().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_Abstract_Schedule::get_date()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/find-action', [
        'label'               => __( 'Find Action', 'fluent-booking' ),
        'description'         => __( 'Find action via ActionScheduler_Store::find_action().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_Store::find_action()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-status-labels', [
        'label'               => __( 'Get Status Labels', 'fluent-booking' ),
        'description'         => __( 'Get status labels via ActionScheduler_Store::get_status_labels().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_Store::get_status_labels()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-local-timezone', [
        'label'               => __( 'Get Local Timezone', 'fluent-booking' ),
        'description'         => __( 'Get local timezone via ActionScheduler_TimezoneHelper::get_local_timezone().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_TimezoneHelper::get_local_timezone()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-hook', [
        'label'               => __( 'Get Hook', 'fluent-booking' ),
        'description'         => __( 'Get hook via ActionScheduler_Action::get_hook().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_Action::get_hook()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-schedule', [
        'label'               => __( 'Get Schedule', 'fluent-booking' ),
        'description'         => __( 'Get schedule via ActionScheduler_Action::get_schedule().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_Action::get_schedule()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-args', [
        'label'               => __( 'Get Args', 'fluent-booking' ),
        'description'         => __( 'Get args via ActionScheduler_Action::get_args().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_Action::get_args()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-group', [
        'label'               => __( 'Get Group', 'fluent-booking' ),
        'description'         => __( 'Get group via ActionScheduler_Action::get_group().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_Action::get_group()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-priority', [
        'label'               => __( 'Get Priority', 'fluent-booking' ),
        'description'         => __( 'Get priority via ActionScheduler_Action::get_priority().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_Action::get_priority()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-entry', [
        'label'               => __( 'Get Entry', 'fluent-booking' ),
        'description'         => __( 'Get entry via ActionScheduler_DBLogger::get_entry().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_DBLogger::get_entry()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-logs', [
        'label'               => __( 'Get Logs', 'fluent-booking' ),
        'description'         => __( 'Get logs via ActionScheduler_DBLogger::get_logs().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_DBLogger::get_logs()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/delete-action', [
        'label'               => __( 'Delete Action', 'fluent-booking' ),
        'description'         => __( 'Delete action via ActionScheduler_DBStore::delete_action().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id'    => [ 'type' => 'integer', 'description' => 'Item ID'               ],
                    'force' => [ 'type' => 'boolean', 'description' => 'Bypass trash', 'default' => false ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_DBStore::delete_action()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-date-3', [
        'label'               => __( 'Get Date', 'fluent-booking' ),
        'description'         => __( 'Get date via ActionScheduler_DBStore::get_date().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_DBStore::get_date()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-claim-filter', [
        'label'               => __( 'Get Claim Filter', 'fluent-booking' ),
        'description'         => __( 'Get claim filter via ActionScheduler_DBStore::get_claim_filter().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_DBStore::get_claim_filter()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-claim-count', [
        'label'               => __( 'Get Claim Count', 'fluent-booking' ),
        'description'         => __( 'Get claim count via ActionScheduler_DBStore::get_claim_count().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_DBStore::get_claim_count()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-claim-id', [
        'label'               => __( 'Get Claim Id', 'fluent-booking' ),
        'description'         => __( 'Get claim id via ActionScheduler_DBStore::get_claim_id().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_DBStore::get_claim_id()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/find-actions-by-claim-id', [
        'label'               => __( 'Find Actions By Claim Id', 'fluent-booking' ),
        'description'         => __( 'Find actions by claim id via ActionScheduler_DBStore::find_actions_by_claim_id().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_DBStore::find_actions_by_claim_id()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-status', [
        'label'               => __( 'Get Status', 'fluent-booking' ),
        'description'         => __( 'Get status via ActionScheduler_DBStore::get_status().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_DBStore::get_status()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/find-action-2', [
        'label'               => __( 'Find Action', 'fluent-booking' ),
        'description'         => __( 'Find action via ActionScheduler_HybridStore::find_action().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_HybridStore::find_action()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/delete-action-2', [
        'label'               => __( 'Delete Action', 'fluent-booking' ),
        'description'         => __( 'Delete action via ActionScheduler_HybridStore::delete_action().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id'    => [ 'type' => 'integer', 'description' => 'Item ID'               ],
                    'force' => [ 'type' => 'boolean', 'description' => 'Bypass trash', 'default' => false ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_HybridStore::delete_action()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-date-4', [
        'label'               => __( 'Get Date', 'fluent-booking' ),
        'description'         => __( 'Get date via ActionScheduler_HybridStore::get_date().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_HybridStore::get_date()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-status-2', [
        'label'               => __( 'Get Status', 'fluent-booking' ),
        'description'         => __( 'Get status via ActionScheduler_HybridStore::get_status().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_HybridStore::get_status()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-claim-count-2', [
        'label'               => __( 'Get Claim Count', 'fluent-booking' ),
        'description'         => __( 'Get claim count via ActionScheduler_HybridStore::get_claim_count().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_HybridStore::get_claim_count()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-claim-id-2', [
        'label'               => __( 'Get Claim Id', 'fluent-booking' ),
        'description'         => __( 'Get claim id via ActionScheduler_HybridStore::get_claim_id().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_HybridStore::get_claim_id()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/find-actions-by-claim-id-2', [
        'label'               => __( 'Find Actions By Claim Id', 'fluent-booking' ),
        'description'         => __( 'Find actions by claim id via ActionScheduler_HybridStore::find_actions_by_claim_id().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_HybridStore::find_actions_by_claim_id()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-entry-2', [
        'label'               => __( 'Get Entry', 'fluent-booking' ),
        'description'         => __( 'Get entry via ActionScheduler_wpCommentLogger::get_entry().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_wpCommentLogger::get_entry()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-logs-2', [
        'label'               => __( 'Get Logs', 'fluent-booking' ),
        'description'         => __( 'Get logs via ActionScheduler_wpCommentLogger::get_logs().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_wpCommentLogger::get_logs()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/delete-comment-count-cache', [
        'label'               => __( 'Delete Comment Count Cache', 'fluent-booking' ),
        'description'         => __( 'Delete comment count cache via ActionScheduler_wpCommentLogger::delete_comment_count_cache().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id'    => [ 'type' => 'integer', 'description' => 'Item ID'               ],
                    'force' => [ 'type' => 'boolean', 'description' => 'Bypass trash', 'default' => false ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_wpCommentLogger::delete_comment_count_cache()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/delete-action-3', [
        'label'               => __( 'Delete Action', 'fluent-booking' ),
        'description'         => __( 'Delete action via ActionScheduler_wpPostStore::delete_action().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id'    => [ 'type' => 'integer', 'description' => 'Item ID'               ],
                    'force' => [ 'type' => 'boolean', 'description' => 'Bypass trash', 'default' => false ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_wpPostStore::delete_action()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-date-5', [
        'label'               => __( 'Get Date', 'fluent-booking' ),
        'description'         => __( 'Get date via ActionScheduler_wpPostStore::get_date().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_wpPostStore::get_date()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-date-gmt', [
        'label'               => __( 'Get Date Gmt', 'fluent-booking' ),
        'description'         => __( 'Get date gmt via ActionScheduler_wpPostStore::get_date_gmt().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_wpPostStore::get_date_gmt()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-claim-count-3', [
        'label'               => __( 'Get Claim Count', 'fluent-booking' ),
        'description'         => __( 'Get claim count via ActionScheduler_wpPostStore::get_claim_count().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_wpPostStore::get_claim_count()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/find-actions-by-claim-id-3', [
        'label'               => __( 'Find Actions By Claim Id', 'fluent-booking' ),
        'description'         => __( 'Find actions by claim id via ActionScheduler_wpPostStore::find_actions_by_claim_id().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_wpPostStore::find_actions_by_claim_id()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-claim-id-3', [
        'label'               => __( 'Get Claim Id', 'fluent-booking' ),
        'description'         => __( 'Get claim id via ActionScheduler_wpPostStore::get_claim_id().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_wpPostStore::get_claim_id()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-status-3', [
        'label'               => __( 'Get Status', 'fluent-booking' ),
        'description'         => __( 'Get status via ActionScheduler_wpPostStore::get_status().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_wpPostStore::get_status()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-source-store', [
        'label'               => __( 'Get Source Store', 'fluent-booking' ),
        'description'         => __( 'Get source store via Config::get_source_store().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: Config::get_source_store()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-source-logger', [
        'label'               => __( 'Get Source Logger', 'fluent-booking' ),
        'description'         => __( 'Get source logger via Config::get_source_logger().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: Config::get_source_logger()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-destination-store', [
        'label'               => __( 'Get Destination Store', 'fluent-booking' ),
        'description'         => __( 'Get destination store via Config::get_destination_store().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: Config::get_destination_store()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-destination-logger', [
        'label'               => __( 'Get Destination Logger', 'fluent-booking' ),
        'description'         => __( 'Get destination logger via Config::get_destination_logger().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: Config::get_destination_logger()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-dry-run', [
        'label'               => __( 'Get Dry Run', 'fluent-booking' ),
        'description'         => __( 'Get dry run via Config::get_dry_run().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: Config::get_dry_run()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-progress-bar', [
        'label'               => __( 'Get Progress Bar', 'fluent-booking' ),
        'description'         => __( 'Get progress bar via Config::get_progress_bar().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: Config::get_progress_bar()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-store-class', [
        'label'               => __( 'Get Store Class', 'fluent-booking' ),
        'description'         => __( 'Get store class via Controller::get_store_class().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: Controller::get_store_class()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-logger-class', [
        'label'               => __( 'Get Logger Class', 'fluent-booking' ),
        'description'         => __( 'Get logger class via Controller::get_logger_class().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: Controller::get_logger_class()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-migration-config-object', [
        'label'               => __( 'Get Migration Config Object', 'fluent-booking' ),
        'description'         => __( 'Get migration config object via Controller::get_migration_config_object().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: Controller::get_migration_config_object()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-next-2', [
        'label'               => __( 'Get Next', 'fluent-booking' ),
        'description'         => __( 'Get next via ActionScheduler_CanceledSchedule::get_next().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_CanceledSchedule::get_next()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/get-recurrence-2', [
        'label'               => __( 'Get Recurrence', 'fluent-booking' ),
        'description'         => __( 'Get recurrence via ActionScheduler_CronSchedule::get_recurrence().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_CronSchedule::get_recurrence()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/update-schema-3-0', [
        'label'               => __( 'Update Schema 3 0', 'fluent-booking' ),
        'description'         => __( 'Update schema 3 0 via ActionScheduler_LoggerSchema::update_schema_3_0().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id'   => [ 'type' => 'integer', 'description' => 'Item ID'             ],
                    'data' => [ 'type' => 'object',  'description' => 'Updated item fields' ],
                ],
                'required'   => [ 'id', 'data' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_LoggerSchema::update_schema_3_0()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/update-schema-5-0', [
        'label'               => __( 'Update Schema 5 0', 'fluent-booking' ),
        'description'         => __( 'Update schema 5 0 via ActionScheduler_StoreSchema::update_schema_5_0().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id'   => [ 'type' => 'integer', 'description' => 'Item ID'             ],
                    'data' => [ 'type' => 'object',  'description' => 'Updated item fields' ],
                ],
                'required'   => [ 'id', 'data' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_StoreSchema::update_schema_5_0()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/list-table-views', [
        'label'               => __( 'List Table Views', 'fluent-booking' ),
        'description'         => __( 'List table views via ActionScheduler_AdminView_Deprecated::list_table_views().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_AdminView_Deprecated::list_table_views()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/list-table-columns', [
        'label'               => __( 'List Table Columns', 'fluent-booking' ),
        'description'         => __( 'List table columns via ActionScheduler_AdminView_Deprecated::list_table_columns().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_AdminView_Deprecated::list_table_columns()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/list-table-sortable-columns', [
        'label'               => __( 'List Table Sortable Columns', 'fluent-booking' ),
        'description'         => __( 'List table sortable columns via ActionScheduler_AdminView_Deprecated::list_table_sortable_columns().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_AdminView_Deprecated::list_table_sortable_columns()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/list-table-column-content', [
        'label'               => __( 'List Table Column Content', 'fluent-booking' ),
        'description'         => __( 'List table column content via ActionScheduler_AdminView_Deprecated::list_table_column_content().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_AdminView_Deprecated::list_table_column_content()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluent-booking/search-post-password', [
        'label'               => __( 'Search Post Password', 'fluent-booking' ),
        'description'         => __( 'Search post password via ActionScheduler_AdminView_Deprecated::search_post_password().', 'fluent-booking' ),
        'category'            => 'fluent-booking',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using FluentBooking - Appointment Scheduling & Booking Solution's PHP API
            // Endpoint: ActionScheduler_AdminView_Deprecated::search_post_password()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

} );
// Scanner summary: 0 REST routes, 0 CPTs, 86 CRUD methods → 86 abilities generated.