<?php
/**
 * Fluent Forms — WP Abilities API adapter
 * Generated by wp-ability-scanner on 2026-03-19
 * Drop into wp-content/mu-plugins/ — zero changes to Fluent Forms required.
 * @license GPL-2.0-or-later
 */
defined( 'ABSPATH' ) || exit;

// Categories use wp_abilities_api_categories_init hook
add_action( 'wp_abilities_api_categories_init', function(): void {
    wp_register_ability_category( 'fluentform', [
        'label'       => __( 'Fluent Forms', 'fluentform' ),
        'description' => __( 'AI abilities for Fluent Forms.', 'fluentform' ),
    ] );
} );

// Abilities use wp_abilities_api_init hook
add_action( 'wp_abilities_api_init', function(): void {

    wp_register_ability( 'fluentform/get-secret-key', [
        'label'               => __( 'Get Secret Key', 'fluentform' ),
        'description'         => __( 'Get secret key via ApiRequest::get_secret_key().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ApiRequest::get_secret_key()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-user-agent', [
        'label'               => __( 'Get User Agent', 'fluentform' ),
        'description'         => __( 'Get user agent via ApiRequest::get_user_agent().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ApiRequest::get_user_agent()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-headers', [
        'label'               => __( 'Get Headers', 'fluentform' ),
        'description'         => __( 'Get headers via ApiRequest::get_headers().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ApiRequest::get_headers()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-name', [
        'label'               => __( 'Get Name', 'fluentform' ),
        'description'         => __( 'Get name via FluentFormWidget::get_name().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: FluentFormWidget::get_name()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-title', [
        'label'               => __( 'Get Title', 'fluentform' ),
        'description'         => __( 'Get title via FluentFormWidget::get_title().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: FluentFormWidget::get_title()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-icon', [
        'label'               => __( 'Get Icon', 'fluentform' ),
        'description'         => __( 'Get icon via FluentFormWidget::get_icon().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: FluentFormWidget::get_icon()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-keywords', [
        'label'               => __( 'Get Keywords', 'fluentform' ),
        'description'         => __( 'Get keywords via FluentFormWidget::get_keywords().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: FluentFormWidget::get_keywords()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-categories', [
        'label'               => __( 'Get Categories', 'fluentform' ),
        'description'         => __( 'Get categories via FluentFormWidget::get_categories().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: FluentFormWidget::get_categories()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-style-depends', [
        'label'               => __( 'Get Style Depends', 'fluentform' ),
        'description'         => __( 'Get style depends via FluentFormWidget::get_style_depends().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: FluentFormWidget::get_style_depends()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-script-depends', [
        'label'               => __( 'Get Script Depends', 'fluentform' ),
        'description'         => __( 'Get script depends via FluentFormWidget::get_script_depends().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: FluentFormWidget::get_script_depends()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-id', [
        'label'               => __( 'Get Id', 'fluentform' ),
        'description'         => __( 'Get id via ActionScheduler_ActionClaim::get_id().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_ActionClaim::get_id()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-actions', [
        'label'               => __( 'Get Actions', 'fluentform' ),
        'description'         => __( 'Get actions via ActionScheduler_ActionClaim::get_actions().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_ActionClaim::get_actions()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-stored-action', [
        'label'               => __( 'Get Stored Action', 'fluentform' ),
        'description'         => __( 'Get stored action via ActionScheduler_ActionFactory::get_stored_action().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_ActionFactory::get_stored_action()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-date', [
        'label'               => __( 'Get Date', 'fluentform' ),
        'description'         => __( 'Get date via ActionScheduler_LogEntry::get_date().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_LogEntry::get_date()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-action-id', [
        'label'               => __( 'Get Action Id', 'fluentform' ),
        'description'         => __( 'Get action id via ActionScheduler_LogEntry::get_action_id().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_LogEntry::get_action_id()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-message', [
        'label'               => __( 'Get Message', 'fluentform' ),
        'description'         => __( 'Get message via ActionScheduler_LogEntry::get_message().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_LogEntry::get_message()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-expiration', [
        'label'               => __( 'Get Expiration', 'fluentform' ),
        'description'         => __( 'Get expiration via ActionScheduler_OptionLock::get_expiration().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_OptionLock::get_expiration()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/delete-old-actions', [
        'label'               => __( 'Delete Old Actions', 'fluentform' ),
        'description'         => __( 'Delete old actions via ActionScheduler_QueueCleaner::delete_old_actions().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id'    => [ 'type' => 'integer', 'description' => 'Item ID'               ],
                    'force' => [ 'type' => 'boolean', 'description' => 'Bypass trash', 'default' => false ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_QueueCleaner::delete_old_actions()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-sources', [
        'label'               => __( 'Get Sources', 'fluentform' ),
        'description'         => __( 'Get sources via ActionScheduler_SystemInformation::get_sources().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_SystemInformation::get_sources()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-versions', [
        'label'               => __( 'Get Versions', 'fluentform' ),
        'description'         => __( 'Get versions via ActionScheduler_Versions::get_versions().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_Versions::get_versions()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-sources-2', [
        'label'               => __( 'Get Sources', 'fluentform' ),
        'description'         => __( 'Get sources via ActionScheduler_Versions::get_sources().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_Versions::get_sources()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/delete-all-action-comments', [
        'label'               => __( 'Delete All Action Comments', 'fluentform' ),
        'description'         => __( 'Delete all action comments via ActionScheduler_WPCommentCleaner::delete_all_action_comments().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id'    => [ 'type' => 'integer', 'description' => 'Item ID'               ],
                    'force' => [ 'type' => 'boolean', 'description' => 'Bypass trash', 'default' => false ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_WPCommentCleaner::delete_all_action_comments()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-datetime-object', [
        'label'               => __( 'Get Datetime Object', 'fluentform' ),
        'description'         => __( 'Get datetime object via ActionScheduler::get_datetime_object().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler::get_datetime_object()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-sortable-columns', [
        'label'               => __( 'Get Sortable Columns', 'fluentform' ),
        'description'         => __( 'Get sortable columns via ActionScheduler_Abstract_ListTable::get_sortable_columns().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_Abstract_ListTable::get_sortable_columns()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-columns', [
        'label'               => __( 'Get Columns', 'fluentform' ),
        'description'         => __( 'Get columns via ActionScheduler_Abstract_ListTable::get_columns().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_Abstract_ListTable::get_columns()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-allowed-concurrent-batches', [
        'label'               => __( 'Get Allowed Concurrent Batches', 'fluentform' ),
        'description'         => __( 'Get allowed concurrent batches via ActionScheduler_Abstract_QueueRunner::get_allowed_concurrent_batches().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_Abstract_QueueRunner::get_allowed_concurrent_batches()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-first-date', [
        'label'               => __( 'Get First Date', 'fluentform' ),
        'description'         => __( 'Get first date via ActionScheduler_Abstract_RecurringSchedule::get_first_date().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_Abstract_RecurringSchedule::get_first_date()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-recurrence', [
        'label'               => __( 'Get Recurrence', 'fluentform' ),
        'description'         => __( 'Get recurrence via ActionScheduler_Abstract_RecurringSchedule::get_recurrence().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_Abstract_RecurringSchedule::get_recurrence()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-next', [
        'label'               => __( 'Get Next', 'fluentform' ),
        'description'         => __( 'Get next via ActionScheduler_Abstract_Schedule::get_next().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_Abstract_Schedule::get_next()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-date-2', [
        'label'               => __( 'Get Date', 'fluentform' ),
        'description'         => __( 'Get date via ActionScheduler_Abstract_Schedule::get_date().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_Abstract_Schedule::get_date()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/find-action', [
        'label'               => __( 'Find Action', 'fluentform' ),
        'description'         => __( 'Find action via ActionScheduler_Store::find_action().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_Store::find_action()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-status-labels', [
        'label'               => __( 'Get Status Labels', 'fluentform' ),
        'description'         => __( 'Get status labels via ActionScheduler_Store::get_status_labels().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_Store::get_status_labels()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-local-timezone', [
        'label'               => __( 'Get Local Timezone', 'fluentform' ),
        'description'         => __( 'Get local timezone via ActionScheduler_TimezoneHelper::get_local_timezone().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_TimezoneHelper::get_local_timezone()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-hook', [
        'label'               => __( 'Get Hook', 'fluentform' ),
        'description'         => __( 'Get hook via ActionScheduler_Action::get_hook().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_Action::get_hook()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-schedule', [
        'label'               => __( 'Get Schedule', 'fluentform' ),
        'description'         => __( 'Get schedule via ActionScheduler_Action::get_schedule().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_Action::get_schedule()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-args', [
        'label'               => __( 'Get Args', 'fluentform' ),
        'description'         => __( 'Get args via ActionScheduler_Action::get_args().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_Action::get_args()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-group', [
        'label'               => __( 'Get Group', 'fluentform' ),
        'description'         => __( 'Get group via ActionScheduler_Action::get_group().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_Action::get_group()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-priority', [
        'label'               => __( 'Get Priority', 'fluentform' ),
        'description'         => __( 'Get priority via ActionScheduler_Action::get_priority().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_Action::get_priority()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-entry', [
        'label'               => __( 'Get Entry', 'fluentform' ),
        'description'         => __( 'Get entry via ActionScheduler_DBLogger::get_entry().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_DBLogger::get_entry()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-logs', [
        'label'               => __( 'Get Logs', 'fluentform' ),
        'description'         => __( 'Get logs via ActionScheduler_DBLogger::get_logs().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_DBLogger::get_logs()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/delete-action', [
        'label'               => __( 'Delete Action', 'fluentform' ),
        'description'         => __( 'Delete action via ActionScheduler_DBStore::delete_action().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id'    => [ 'type' => 'integer', 'description' => 'Item ID'               ],
                    'force' => [ 'type' => 'boolean', 'description' => 'Bypass trash', 'default' => false ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_DBStore::delete_action()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-date-3', [
        'label'               => __( 'Get Date', 'fluentform' ),
        'description'         => __( 'Get date via ActionScheduler_DBStore::get_date().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_DBStore::get_date()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-claim-filter', [
        'label'               => __( 'Get Claim Filter', 'fluentform' ),
        'description'         => __( 'Get claim filter via ActionScheduler_DBStore::get_claim_filter().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_DBStore::get_claim_filter()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-claim-count', [
        'label'               => __( 'Get Claim Count', 'fluentform' ),
        'description'         => __( 'Get claim count via ActionScheduler_DBStore::get_claim_count().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_DBStore::get_claim_count()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-claim-id', [
        'label'               => __( 'Get Claim Id', 'fluentform' ),
        'description'         => __( 'Get claim id via ActionScheduler_DBStore::get_claim_id().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_DBStore::get_claim_id()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/find-actions-by-claim-id', [
        'label'               => __( 'Find Actions By Claim Id', 'fluentform' ),
        'description'         => __( 'Find actions by claim id via ActionScheduler_DBStore::find_actions_by_claim_id().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_DBStore::find_actions_by_claim_id()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-status', [
        'label'               => __( 'Get Status', 'fluentform' ),
        'description'         => __( 'Get status via ActionScheduler_DBStore::get_status().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_DBStore::get_status()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/find-action-2', [
        'label'               => __( 'Find Action', 'fluentform' ),
        'description'         => __( 'Find action via ActionScheduler_HybridStore::find_action().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_HybridStore::find_action()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/delete-action-2', [
        'label'               => __( 'Delete Action', 'fluentform' ),
        'description'         => __( 'Delete action via ActionScheduler_HybridStore::delete_action().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id'    => [ 'type' => 'integer', 'description' => 'Item ID'               ],
                    'force' => [ 'type' => 'boolean', 'description' => 'Bypass trash', 'default' => false ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_HybridStore::delete_action()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-date-4', [
        'label'               => __( 'Get Date', 'fluentform' ),
        'description'         => __( 'Get date via ActionScheduler_HybridStore::get_date().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_HybridStore::get_date()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-status-2', [
        'label'               => __( 'Get Status', 'fluentform' ),
        'description'         => __( 'Get status via ActionScheduler_HybridStore::get_status().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_HybridStore::get_status()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-claim-count-2', [
        'label'               => __( 'Get Claim Count', 'fluentform' ),
        'description'         => __( 'Get claim count via ActionScheduler_HybridStore::get_claim_count().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_HybridStore::get_claim_count()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-claim-id-2', [
        'label'               => __( 'Get Claim Id', 'fluentform' ),
        'description'         => __( 'Get claim id via ActionScheduler_HybridStore::get_claim_id().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_HybridStore::get_claim_id()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/find-actions-by-claim-id-2', [
        'label'               => __( 'Find Actions By Claim Id', 'fluentform' ),
        'description'         => __( 'Find actions by claim id via ActionScheduler_HybridStore::find_actions_by_claim_id().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_HybridStore::find_actions_by_claim_id()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-entry-2', [
        'label'               => __( 'Get Entry', 'fluentform' ),
        'description'         => __( 'Get entry via ActionScheduler_wpCommentLogger::get_entry().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_wpCommentLogger::get_entry()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-logs-2', [
        'label'               => __( 'Get Logs', 'fluentform' ),
        'description'         => __( 'Get logs via ActionScheduler_wpCommentLogger::get_logs().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_wpCommentLogger::get_logs()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/delete-comment-count-cache', [
        'label'               => __( 'Delete Comment Count Cache', 'fluentform' ),
        'description'         => __( 'Delete comment count cache via ActionScheduler_wpCommentLogger::delete_comment_count_cache().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id'    => [ 'type' => 'integer', 'description' => 'Item ID'               ],
                    'force' => [ 'type' => 'boolean', 'description' => 'Bypass trash', 'default' => false ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_wpCommentLogger::delete_comment_count_cache()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/delete-action-3', [
        'label'               => __( 'Delete Action', 'fluentform' ),
        'description'         => __( 'Delete action via ActionScheduler_wpPostStore::delete_action().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id'    => [ 'type' => 'integer', 'description' => 'Item ID'               ],
                    'force' => [ 'type' => 'boolean', 'description' => 'Bypass trash', 'default' => false ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_wpPostStore::delete_action()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-date-5', [
        'label'               => __( 'Get Date', 'fluentform' ),
        'description'         => __( 'Get date via ActionScheduler_wpPostStore::get_date().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_wpPostStore::get_date()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-date-gmt', [
        'label'               => __( 'Get Date Gmt', 'fluentform' ),
        'description'         => __( 'Get date gmt via ActionScheduler_wpPostStore::get_date_gmt().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_wpPostStore::get_date_gmt()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-claim-count-3', [
        'label'               => __( 'Get Claim Count', 'fluentform' ),
        'description'         => __( 'Get claim count via ActionScheduler_wpPostStore::get_claim_count().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_wpPostStore::get_claim_count()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/find-actions-by-claim-id-3', [
        'label'               => __( 'Find Actions By Claim Id', 'fluentform' ),
        'description'         => __( 'Find actions by claim id via ActionScheduler_wpPostStore::find_actions_by_claim_id().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_wpPostStore::find_actions_by_claim_id()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-claim-id-3', [
        'label'               => __( 'Get Claim Id', 'fluentform' ),
        'description'         => __( 'Get claim id via ActionScheduler_wpPostStore::get_claim_id().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_wpPostStore::get_claim_id()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-status-3', [
        'label'               => __( 'Get Status', 'fluentform' ),
        'description'         => __( 'Get status via ActionScheduler_wpPostStore::get_status().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_wpPostStore::get_status()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-source-store', [
        'label'               => __( 'Get Source Store', 'fluentform' ),
        'description'         => __( 'Get source store via Config::get_source_store().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: Config::get_source_store()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-source-logger', [
        'label'               => __( 'Get Source Logger', 'fluentform' ),
        'description'         => __( 'Get source logger via Config::get_source_logger().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: Config::get_source_logger()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-destination-store', [
        'label'               => __( 'Get Destination Store', 'fluentform' ),
        'description'         => __( 'Get destination store via Config::get_destination_store().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: Config::get_destination_store()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-destination-logger', [
        'label'               => __( 'Get Destination Logger', 'fluentform' ),
        'description'         => __( 'Get destination logger via Config::get_destination_logger().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: Config::get_destination_logger()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-dry-run', [
        'label'               => __( 'Get Dry Run', 'fluentform' ),
        'description'         => __( 'Get dry run via Config::get_dry_run().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: Config::get_dry_run()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-progress-bar', [
        'label'               => __( 'Get Progress Bar', 'fluentform' ),
        'description'         => __( 'Get progress bar via Config::get_progress_bar().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: Config::get_progress_bar()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-store-class', [
        'label'               => __( 'Get Store Class', 'fluentform' ),
        'description'         => __( 'Get store class via Controller::get_store_class().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: Controller::get_store_class()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-logger-class', [
        'label'               => __( 'Get Logger Class', 'fluentform' ),
        'description'         => __( 'Get logger class via Controller::get_logger_class().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: Controller::get_logger_class()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-migration-config-object', [
        'label'               => __( 'Get Migration Config Object', 'fluentform' ),
        'description'         => __( 'Get migration config object via Controller::get_migration_config_object().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: Controller::get_migration_config_object()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-next-2', [
        'label'               => __( 'Get Next', 'fluentform' ),
        'description'         => __( 'Get next via ActionScheduler_CanceledSchedule::get_next().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_CanceledSchedule::get_next()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/get-recurrence-2', [
        'label'               => __( 'Get Recurrence', 'fluentform' ),
        'description'         => __( 'Get recurrence via ActionScheduler_CronSchedule::get_recurrence().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id' => [ 'type' => 'integer', 'description' => 'Item ID' ],
                ],
                'required'   => [ 'id' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_CronSchedule::get_recurrence()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/update-schema-3-0', [
        'label'               => __( 'Update Schema 3 0', 'fluentform' ),
        'description'         => __( 'Update schema 3 0 via ActionScheduler_LoggerSchema::update_schema_3_0().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id'   => [ 'type' => 'integer', 'description' => 'Item ID'             ],
                    'data' => [ 'type' => 'object',  'description' => 'Updated item fields' ],
                ],
                'required'   => [ 'id', 'data' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_LoggerSchema::update_schema_3_0()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/update-schema-5-0', [
        'label'               => __( 'Update Schema 5 0', 'fluentform' ),
        'description'         => __( 'Update schema 5 0 via ActionScheduler_StoreSchema::update_schema_5_0().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'id'   => [ 'type' => 'integer', 'description' => 'Item ID'             ],
                    'data' => [ 'type' => 'object',  'description' => 'Updated item fields' ],
                ],
                'required'   => [ 'id', 'data' ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_StoreSchema::update_schema_5_0()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/list-table-views', [
        'label'               => __( 'List Table Views', 'fluentform' ),
        'description'         => __( 'List table views via ActionScheduler_AdminView_Deprecated::list_table_views().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_AdminView_Deprecated::list_table_views()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/list-table-columns', [
        'label'               => __( 'List Table Columns', 'fluentform' ),
        'description'         => __( 'List table columns via ActionScheduler_AdminView_Deprecated::list_table_columns().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_AdminView_Deprecated::list_table_columns()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/list-table-sortable-columns', [
        'label'               => __( 'List Table Sortable Columns', 'fluentform' ),
        'description'         => __( 'List table sortable columns via ActionScheduler_AdminView_Deprecated::list_table_sortable_columns().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_AdminView_Deprecated::list_table_sortable_columns()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/list-table-column-content', [
        'label'               => __( 'List Table Column Content', 'fluentform' ),
        'description'         => __( 'List table column content via ActionScheduler_AdminView_Deprecated::list_table_column_content().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_AdminView_Deprecated::list_table_column_content()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

    wp_register_ability( 'fluentform/search-post-password', [
        'label'               => __( 'Search Post Password', 'fluentform' ),
        'description'         => __( 'Search post password via ActionScheduler_AdminView_Deprecated::search_post_password().', 'fluentform' ),
        'category'            => 'fluentform',
        'input_schema'        => [
                        'type'       => 'object',
                'properties' => [
                    'per_page' => [ 'type' => 'integer', 'description' => 'Results per page', 'default' => 10 ],
                    'page'     => [ 'type' => 'integer', 'description' => 'Page number',       'default' => 1  ],
                    'search'   => [ 'type' => 'string',  'description' => 'Search term'                       ],
                ],
        ],
        'execute_callback'    => function( array $input ): array|\WP_Error {
            // TODO: implement using Fluent Forms's PHP API
            // Endpoint: ActionScheduler_AdminView_Deprecated::search_post_password()
            return [ 'error' => 'Callback not yet implemented' ];
        },
        'permission_callback' => function(): bool {
            return is_user_logged_in();
        },
    ] );

} );
// Scanner summary: 0 REST routes, 0 CPTs, 82 CRUD methods → 82 abilities generated.